name: Build Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 初始化 GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'

      - name: 计算版本 Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          overrideConfig: |
            assembly-versioning-scheme=MajorMinorPatchTag
            assembly-file-versioning-format="{Major}.{Minor}.{Patch}.{BuildMetaData ?? 0}"

      - name: 初始化 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          architecture: x64

      - name: 初始化 Rust 工具链
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: 还原依赖
        run: flutter pub get

      - name: 生成代码
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 构建项目
        shell: pwsh
        run: |-
          flutter build windows `
            --build-name=${{ steps.gitversion.outputs.majorMinorPatch }} `
            --build-number=${{ steps.gitversion.outputs.buildMetaData }}

      - name: 上传产物
        id: binary-artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: build/windows/x64/runner/Release/**/*
          compression-level: 9

      - name: 安装 NSIS
        shell: pwsh
        run: choco install nsis -y

      - name: 打包成单一 EXE
        shell: pwsh
        run: makensis windows/pixez.nsi

      - name: 上传 EXE Installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: pixez-installer.exe
          compression-level: 9

      - name: 生成校验和
        shell: pwsh
        run: |-
          Write-Output '### Build Success :rocket:' >> $env:GITHUB_STEP_SUMMARY
          Write-Output '|File|SHA256|' >> $env:GITHUB_STEP_SUMMARY
          Write-Output '|:-|:-:|' >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|[binary](${{ steps.binary-artifact.outputs.artifact-url }})|${{ steps.binary-artifact.outputs.artifact-digest }}|" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|[installer](${{ steps.installer.outputs.artifact-url }})|${{ steps.installer.outputs.artifact-digest }}|" >> $env:GITHUB_STEP_SUMMARY
